### ISSUE TITLE
convert Json-to-cobol

### ISSUE THREAD

**Issue by FlavioRossi** [bmTas/CobolToJson#1]
Hi! First of all, I wanna thank you for the excellent lib that you create!
I wanna ask you if you are thinking in add the feature to convert Json to Cobol

**Comment by bmTas** [comment]
There is limited support for converting Json to Cobol via the
**Cobol2Json.newCobol2Json(..)** builder

~~~java
		Cobol2Json.newCobol2Json(Cbl2JsonCode.getFullName("DTAR020.cbl"))
		  .setFont("cp037")
		  .setFileOrganization(IFileStructureConstants.IO_FIXED_LENGTH) 
		  .setSplitCopybook(CopybookLoader.SPLIT_NONE)
		  
		  .jsonArrayToCobolFile("G:/Temp/DTAR020_tst1_normal.json", "G:/Temp/DTAR020_tst1_normal_json.bin")
		  
		  .setTagFormat(IReformatFieldNames.RO_UNDERSCORE)
		  .jsonArrayToCobolFile("G:/Temp/DTAR020_tst1.bin.json", "G:/Temp/DTAR020_tst1_bin_json.bin")
		  ;
~~~

Conversion methods include
* **jsonArrayToCobolFile** this method will convert a json array to a file
* **jsonArrayToCobolLines** this method converts a json array to a list of cobol records
* **jsonObjectToCobolFile** Convert a json object to a Cobol record
* **

There are some limitations though:

* Field names must be unique
* Limits on what translations are possible

**Comment by FlavioRossi** [comment]
Thanks you! I trying to convert this json to cobol with this copybook, but it gives me an error when trying to convert the "occurs of APELLIDO", this can be couse the limitations that the field names must be unique?, so we cant convert occurs ?

```

InputStream copybookFile = new ByteArrayInputStream(copybook.getBytes(StandardCharsets.UTF_8));
        try {
            Cobol2Json.newCobol2Json(copybookFile, "generic")
                .setFont("utf8")
                .setDialect(ICopybookDialects.FMT_OC_MICRO_FOCUS)
                .setSplitCopybook(ICobolSplitOptions.SPLIT_NONE)
                .setTagFormat(IReformatFieldNames.RO_UNDERSCORE)
                .jsonArrayToCobolLines(new StringReader(data))
                .stream()
                .forEach(line -> {
                    System.out.println(line.getFullLine());
                });
        } catch (IOException e) {
            Log.error("Error");
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
```
        
```
01  EMPLEADOS.
           03 NOMBRE           PIC X(10).
           03 APELLIDO         OCCURS 5 PIC X(10).
           03 ID                       PIC Z(07)9.
```


```
{
        "NOMBRE": "FLAVIO",
        "APELLIDO": [
            "ROSSI", "PEREZ", "ALBERTO", "GÛEMES", "GONZÁLEZ"
        ],
        "ID": 1004
}
```

```
org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Field: "APELLIDO" does not exist !!!



        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:452)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invokePropagateNotFound$6(SynchronousDispatcher.java:275)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:260)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:86)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Field: "APELLIDO" does not exist !!!
        at net.sf.JRecord.Details.BaseLine.getFieldValue(BaseLine.java:82)
        at net.sf.cobolToJson.impl.readJson.AFieldsToJRecLine.updateField(AFieldsToJRecLine.java:29)
        at net.sf.cobolToJson.impl.readJson.JsonToCobol.readJson(JsonToCobol.java:69)
        at net.sf.cobolToJson.impl.readJson.JsonToCobol.readJson(JsonToCobol.java:30)
        at net.sf.cobolToJson.impl.Cobol2JsonImp.jsonArrayToCobolLines(Cobol2JsonImp.java:782)
        at org.apex.cobolConverting.infrastructure.JRecordJsonToCobol.jsonToCobol(JRecordJsonToCobol.java:42)
        at org.apex.cobolConverting.infrastructure.JRecordJsonToCobol_ClientProxy.jsonToCobol(Unknown Source)
        at org.apex.cobolConverting.application.ConvertJsonToCobol.handle(ConvertJsonToCobol.java:15)
        at org.apex.cobolConverting.application.ConvertJsonToCobol_ClientProxy.handle(Unknown Source)
        at org.apex.cobolConverting.Resources.jsonToCobol(Resources.java:75)
        at org.apex.cobolConverting.Resources_ClientProxy.jsonToCobol(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        ... 17 more
```

**Comment by bmTas** [comment]
In the process of fixing

**Comment by bmTas** [comment]
I have made some fixes to the json-to-cobol code.

You using the **jsonArrayToCobolLines** with the wrong data. jsonArrayToCobolLines is intended to work with an array of lines:

~~~
    [{line-1 json},
    {line-2 json},
    ...
    ]
~~~

You could add [] to your json:

~~~
[{
        "NOMBRE": "FLAVIO",
        "APELLIDO": [
            "ROSSI", "PEREZ", "ALBERTO", "GÛEMES", "GONZÁLEZ"
        ],
        "ID": 1004
}]
~~~ 

or use the new **jsonObjectToCobolLine** method

           AbstractLine line = Cobol2Json.newCobol2Json(copybookFile, "generic")
                .setFont("utf8")
                .setDialect(ICopybookDialects.FMT_OC_MICRO_FOCUS)
                .setSplitCopybook(ICobolSplitOptions.SPLIT_NONE)
                .setTagFormat(IReformatFieldNames.RO_UNDERSCORE)
                .jsonObjectToCobolLine(new StringReader(data));
            
            System.out.println(line.getFullLine());

---

I will revise/revamp the User Interface, it has gotten to complicated/messy

**Comment by FlavioRossi** [comment]
Thanks you Bruce! I tried it and it worked excellent, I close the issue, thanks you for the quick solve!
